[package]
name = "openrpc-rs"
version = "0.1.0"
authors = ["fikgol <hit.cs.lijun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = {git = "https://github.com/starcoinorg/schemars", rev="8ada318f4283a4dbb5adeea8a31a8db6a05e0f4d"}
serde_json = "1.0"
serde = "1.0"
